name: Production Deployment
on:
  push:
    branches: 
      - main
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "*,!docker,!.vscode,!.git,!.github,!docker-compose.yml"
          target: ${{ secrets.DEPLOY_SSH_PATH_STAGING }}
      - name: Executing remote ssh command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_SSH_PATH_PRODUCTION }}
            /usr/local/php83/bin/php /cvbin/composer install --no-progress --no-dev --optimize-autoloader
            /usr/local/php83/bin/php ./vendor/bin/kirby scaffold
            /usr/local/php83/bin/php ./vendor/bin/kirby clear:cache uuid
            /usr/local/php83/bin/php ./vendor/bin/kirby clear:cache pages
            /usr/local/php83/bin/php ./vendor/bin/kirby clear:cache uuid:populate
