name: Staging Deployment
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "*,!docker/*,!.vscode/*,!.git/*,!.github/*,!docker-compose.yml"
          target: ${{ secrets.DEPLOY_SSH_PATH_STAGING }}
      - name: Executing remote ssh command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            ${{ secrets.DEPLOY_SSH_KEY }} composer install --no-progress --no-dev --optimize-autoloader --working-dir ${{ secrets.DEPLOY_SSH_PATH_STAGING }}
            php ${{ secrets.DEPLOY_SSH_PATH_STAGING }}/vendor/bin/kirby scaffold
